fabricdb_elt:
  target: prod
  outputs:
    prod:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: ttcxzh37dhhetma2y22gr4ayd4-2ja77tnmhs7e7l5wmr553l6stm.database.fabric.microsoft.com
      port: 1433
      database: fabricDB-e577ac96-a415-4d43-839c-a690ceace260
      schema: mart
      encrypt: true
      trust_cert: false
      authentication: ActiveDirectoryServicePrincipal
      client_id: "{{ env_var('DBT_SP_CLIENT_ID') }}"
      client_secret: "{{ env_var('DBT_SP_CLIENT_SECRET') }}"
      tenant_id: "{{ env_var('DBT_SP_TENANT_ID') }}"