version: 2

models:
  - name: customer_dim
    description: "Dimension table with cleaned and enriched customer data"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique

      - name: customer_name
        description: "Full name of the customer"

      - name: customer_email
        description: "Email address of the customer"

      - name: city
        description: "City where the customer resides"

  - name: products_dim
    description: "Dimension table listing products available for sale"
    columns:
      - name: product_id
        description: "Unique identifier for each product"
        tests:
          - not_null
          - unique

      - name: product_name
        description: "Name or label of the product"

      - name: product_category
        description: "Category of product"

  - name: orders_fact
    description: "Fact table summarizing orders with total revenue and item counts"
    columns:
      - name: order_id
        description: "Order ID"
        tests:
          - not_null

      - name: item_id
        description: "Unique identifier for each order item"
        tests:
          - not_null

      - name: customer_id
        description: "Customer who placed the order"
        tests:
          - not_null
          - relationships:
              to: ref('customer_dim')
              field: customer_id

      - name: order_date
        description: "Date the order was placed"

      - name: line_total
        description: "Total value of the order"

      - name: quantity
        description: "Total quantity of products sold in the order"

      - name: product_id
        description: "Product sold in the order"
        tests:
          - not_null
          - relationships:
              to: ref('products_dim')
              field: product_id

