version: 2

sources:
  - name: fabricdb  # 👈 Name you'll reference in source('fabricdb', 'customers')
    schema: stg
    tables:
      - name: customers
      - name: orders
      - name: products
      - name: order_items
