name: "Deploy DBT Project to Fabric"

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dbt and dependencies
        run: |
          pip install dbt-core==1.8.7 dbt-sqlserver==1.8.7

      - name: Decode base64 and create profiles.yml
        shell: bash
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML_B64 }}" | base64 --decode > ~/.dbt/profiles.yml

      - name: Run dbt deps
        run: dbt deps --project-dir fabricdb_elt

      - name: Run dbt build
        env:
          DBT_SP_CLIENT_ID: ${{ secrets.DBT_SP_CLIENT_ID }}
          DBT_SP_CLIENT_SECRET: ${{ secrets.DBT_SP_CLIENT_SECRET }}
          DBT_SP_TENANT_ID: ${{ secrets.DBT_SP_TENANT_ID }}
        run: dbt build --project-dir fabricdb_elt --target prod