name: "Deploy DBT Project to Fabric"

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DBT_SP_CLIENT_ID: ${{ secrets.DBT_SP_CLIENT_ID }}
      DBT_SP_CLIENT_SECRET: ${{ secrets.DBT_SP_CLIENT_SECRET }}
      DBT_SP_TENANT_ID: ${{ secrets.DBT_SP_TENANT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dbt and dependencies
        run: |
          pip install dbt-core==1.8.7 dbt-sqlserver==1.8.7

      - name: Create dbt profile from secret
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > ~/.dbt/profiles.yml

      - name: Run dbt deps
        run: dbt deps --project-dir fabricdb_elt

      - name: Run dbt build
        run: dbt build --project-dir fabricdb_elt --target prod